- name: Install Apache (httpd)
  yum:
    name: httpd
    state: present
    update_cache: yes

- name: Verify Apache installation
  command: httpd -v
  register: apache_version
  failed_when: apache_version.rc != 0
  changed_when: false

- name: Enable and start Apache service
  service:
    name: httpd
    state: started
    enabled: yes

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    creates: /var/www/html/wordpress

- name: Set permissions for WordPress directory
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: apache
    group: apache
    recurse: yes

